version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql_host
    environment:
#      - MYSQL_DATABASE
#      - MYSQL_USER
#      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306